version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mindsphere-events"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1h40v4jxs5jo8"
s3_prefix = "mindsphere-events"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
profile = "siemens"
