AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  siemens-iot-data-migration-lambda-events

  Sample SAM Template for siemens-iot-data-migration-lambda-events

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  MindSphereEventsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: events_processor/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        MindSphereEvents:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MindSphereEventsApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  MindSphereEventsFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt MindSphereEventsFunction.Arn
  MindSphereEventsFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt MindSphereEventsFunctionRole.Arn
